# MkDocs configuration file

site_name: <Project_Name>
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Usage: 'usage.md'
    - Contributing: 'contributing.md'
    - Authors: 'authors.md'
    - History: 'history.md'
theme: readthedocs
