# Config file for automatic testing at circleci.com

version: 2

jobs:
  py37_tests:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install-dependencies
            make install-dependencies-test
      - run:
          name: Lint
          command: make lint
      - run:
          name: Tests
          command: make test
      - run:
          name: Coverage
          command: |  # must define CODECOV_TOKEN enviroment variable in CircleCI
            make coverage
            python -m coverage xml
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  run_tests:
    jobs:
      - py37_tests
